### ISSUE TITLE
support zoom level > 14

### ISSUE THREAD

**Issue by markuman** [uktrade/mbtiles-s3-server#2]
it seems that it stops at level 14, while tileserver-gl zooms beyond 14 on the same mbtiles file.

**Comment by michalc** [comment]
I have to admit some ignorance - should this sort of overzooming be possible just in the client side, or does the server have to be involved, responding with tiles of higher zoom levels?

**Comment by michalc** [comment]
So removing maxZoom in the client allows zooming, but all the map data disappears... but...

... So right now the server returns a 404 when it can't find a tile, .e.g. at the higher zoom levels when things disappear. But interestingly if I make it return a 500, then that seems to let the MapLibre client overzoom without anything disappearing. I guess I can change the server to return 500s if something can't be found? Although that does seem a bit odd...

**Comment by michalc** [comment]
Ah found a less hacky mechanism - the maximum zoom level of tileset must be specified in the style.json, and then the client knows not to try to fetch higher zoom levels than that, and the client can then overzoom. Will see if I can make that change

**Comment by michalc** [comment]
Done, and released in [v0.0.13](https://pypi.org/project/mbtiles-s3-server/0.0.13/).

There are now a couple more environment variables needed per tileset, e.g. `MBTILES__1__MIN_ZOOM` and `MBTILES__1__MAX_ZOOM`, as the [Example usage](https://github.com/uktrade/mbtiles-s3-server#example-usage).

For OpenStreetMap tiles, these would probably be 0 and 14 in most cases

**Comment by markuman** [comment]
hmmm it did not work here when starting with `MBTILES__1__MIN_ZOOM=0 MBTILES__1__MAX_ZOOM=20`

```
$ pip list|grep mbt
mbtiles-s3-server      0.0.14
```

https://osm.osuv.de/

to compare with tile-gl: https://maps.osuv.de/styles/osm-bright/#17.88/52.519167/13.405508

furthermore I noticed a 404 in the firefox console. I don't not if it is related
```
ource map error: Error: request failed with status 404
Resource URL: https://osm.osuv.de/v1/static/maplibre-gl@2.1.9/maplibre-gl.js
Source Map URL: maplibre-gl.js.map
```

**Comment by michalc** [comment]
Ah - `MBTILES__1__MAX_ZOOM=20` - this should probably be 14 for OpenMapTiles. It's not how much the client is allowed to zoom, but the highest zoom level in the tileset. If you want to allow the client to zoom to 20, then you specify `maxZoom: 14` in the client config, so something like:

```javascript
 var map = new maplibregl.Map({
        ...
        maxZoom: 20
})
```

(Also I've changed the example in the README - I've removed the `maxZoom` item

**Comment by michalc** [comment]
(Also - I'm quite impressed by the performance at https://osm.osuv.de/ - can I ask what it's running on?)

**Comment by markuman** [comment]
> (Also - I'm quite impressed by the performance at https://osm.osuv.de/ - can I ask what it's running on?)

Me too, The smallest and cheapest ec2 instance in eu-central. t4g.nano (arm, 2 cores, 512MB memory)

**Comment by markuman** [comment]
And still a single python process. no gunicorn or bjoern.
